create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  name text unique not null,
  description text
);

create table if not exists public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role_id bigint not null references public.roles(id) on delete cascade,
  created_at timestamptz default now(),
  unique(user_id, role_id)
);

insert into public.roles(name, description) values
('customer','Customer'),
('product_admin','Product Administrator'),
('fulfilment_employee','Order Fulfilment Employee'),
('business_manager','Business Manager'),
('system_admin','System Administrator'),
('reseller','Reseller')
on conflict (name) do nothing;
